#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    session_path=$1
else
    session_path=$(find ~ ~/personal/ -mindepth 1 -maxdepth 2 -type d | grep -v -e .cache -e .git -e _logs | fzf)
fi

session_name=$(basename "$session_path" | tr . _)

if ! tmux has-session -t "$session_name" 2> /dev/null; then
    tmux new-session -s "$session_name" -c "$session_path" -d
fi

tmux switch-client -t "$session_name"
