#!/usr/bin/env bash

session=$(find ~ ~/personal/ -mindepth 1 -maxdepth 2 -type d | grep -v -e .cache -e .git -e _logs | fzf)
session_name=$(basename "$session" | tr . _)

if ! tmux has-session -t "$session_name" 2> /dev/null; then
    tmux new-session -s "$session_name" -c "$session" -d
fi

tmux switch-client -t "$session_name"
