---
- hosts: localhost
  become: no
  gather_facts: no
  pre_tasks:
    - name: Update packages
      become: yes
      apt:
        update_cache: true
      tags:
        - always

  tasks:
    - name: Install steps
      include_tasks: 
        file: "tasks/{{ item }}.yml"
        apply:
          tags: "{{ item }}"
      loop:
        - build_tools
        - utils
        - programming_languages
        - nvim
        - zsh
        - pwsh
        - dotfiles
      tags: always

  post_tasks:
    - name: Run nvim packer
      ansible.builtin.shell: nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
      loop:
        - 1
        - 2
